package site.daska.app;

import android.os.Bundle;
import android.webkit.WebView;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        // TODO before any Play Store release build: gate this behind a
        // debug check (see BuildConfig.DEBUG option) so remote inspection
        // isn't left enabled in production. Unconditional for now, since
        // BuildConfig isn't generated by this project's build config.
        WebView.setWebContentsDebuggingEnabled(true);

        setTheme(R.style.AppTheme_NoActionBar);
        super.onCreate(savedInstanceState);
    }
}